# Generated by Django 4.0.5 on 2022-07-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bike', models.CharField(max_length=20)),
                ('buy_date', models.DateField(null=True)),
            ],
        ),
    ]
