# Generated by Django 4.0.5 on 2022-07-25 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_member_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=500)),
                ('author', models.CharField(max_length=20)),
                ('creation_date', models.DateField(verbose_name=datetime.datetime(2022, 7, 25, 2, 20, 25, 574119))),
            ],
        ),
    ]
