# Generated by Django 4.0.5 on 2022-07-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='creation_date',
            field=models.DateField(null=True),
        ),
    ]
