# Generated by Django 4.0.5 on 2022-07-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('moto', models.CharField(max_length=20)),
                ('fecha_compra', models.DateField(null=True)),
            ],
        ),
    ]
